### ISSUE TITLE
Scroll if not in View

### ISSUE THREAD

**Issue by liviurad** [Nolanus/ngx-page-scroll#166]
Maybe there is already a way to do this, but I didn't find it. 
Anyways, I would like to scroll to the target only if it is not in view, plus an offset would be even cooler :)

**Comment by Nolanus** [comment]
Hi @liviurad,

thanks for the suggestion. At the moment there's no build-in way of doing that as it requires "reading" the scroll position which I tried to keep out of the library. However, your described situation sounds like a very valid scenario to me, so I'll put it on the ToDo list. Unfortunately I can't provide an estimate on how long it will take.

**Comment by lisandropat** [comment]
Any updates on this? Trying to use directive scroll from my navbar that is offset to a wrapped div but ngx-page-scroll just scrolls 5px and stops scrolling...

**Comment by Nolanus** [comment]
Hi @lisandropat,
a draft version of this feature is currently available in the develop branch. I'll have to test is a little further before releasing it.  Feel free to try it in your own and let me know any feedback (clone the repo, execute `npm run build:lib` and copy the dist files into your `node_modules` folder).

**Comment by Nolanus** [comment]
Feature addressed with `scrollInView` property. To not change the current behavior, set this to false to _not_ start a scroll animation when the target pixel is already within the view port.
