### ISSUE TITLE
AOT error: Unexpected value CommonModule

### ISSUE THREAD

**Issue by zaguini** [Nolanus/ngx-page-scroll#218]
I'm trying to build my project with AOT enable, but at 92% it stucks and give me this error message:
`ERROR in Unexpected value 'CommonModule' imported by the module 'Ng2PageScrollModule'`

Version: `4.0.0-beta.4`

Disabling AOT, works fine, but build size is too large. Is there a workaround?

EDIT: Updating to `4.0.0-beta.11` gives me another error:

`ERROR in Cannot read property 'replace' of undefined

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\xampp\htdocs\node\ecs-score-front-wp\src`

**Comment by Nolanus** [comment]
Hi @zaguini,

as no direct call to a `replace` method is done by this libraries code could you please verify that it is caused by this or try getting a longer stacktrace (maybe by using `--verbose`)

**Comment by zaguini** [comment]
Trying to bundle with `--verbose` didn't give me a more clear explanation... Same thing :/ I think it is something related to the version. Looks incompatible.

**Comment by Nolanus** [comment]
A project compiles with aot enabled when using ngxPageScroll:

> $ng build --prod
Date: 2018-04-04T12:51:22.116Z
Hash: 6420a5a81e76a318ef81
Time: 25140ms
chunk {0} main.5c7a94aadeb8b99200e9.bundle.js (main) 787 kB [initial] [rendered]
chunk {1} polyfills.3d02b7f5d2df1c5a98b9.bundle.js (polyfills) 59.7 kB [initial] [rendered]
chunk {2} styles.957de70df40b78b2e821.bundle.css (styles) 49.4 kB [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

Size reference without aot
> $ng build
Date: 2018-04-04T12:51:45.855Z
Hash: 6250edaa7803d65b50b7
Time: 17163ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 3.89 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 82.8 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 205 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 74.8 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 6.11 MB [initial] [rendered]
