### ISSUE TITLE
How to catch pageScrollFinish on PageScrollService?

### ISSUE THREAD

**Issue by rui-cruz** [Nolanus/ngx-page-scroll#242]
Is there a promise or something?

p.s - You should mention on docs that the # is required.

Thank you!

**Comment by Nolanus** [comment]
When creating a `PageScrollInstance` using the factory method `PageScrollInstance.newInstance` you may provide an `EventEmitter` that will be used to notify you about the pageScrollFinish.

```
PageScrollInstance.newInstance({
    // Other props here
   pageScrollFinishListener: this.pageScrollFinish
});
```

It is not required to add the `#` in front of the scroll target, any valid css selector will do.
