### ISSUE TITLE
scroll to a child component which gets shown from the parent component on click event.

### ISSUE THREAD

**Issue by 1sam19** [Nolanus/ngx-page-scroll#243]
i have a parent component and a child component. initially the child component is hidden and it gets activated on click of a button where i am using scroll to pagescroll herf by passing the id of my child component. the scroll works fine when the component is not hidden on the load of parent component.
any way to achieve this?

**Comment by Nolanus** [comment]
The scroll target needs to be in the DOM when the scroll animation starts. If it cannot be found, no scroll animation starts.
In assume you're using `ngIf` to hide and show your child component. This does not result in the child component to be immediately present in the DOM after changing the condition (e.g. your `showChildComp` variable). Thus the scroll animation get's triggered too early.
Consider delaying it by subscribing to any possible event or use `setTimeout(() => {/*trigger scroll*/}, 0)` as last resort.
