### ISSUE TITLE
Metdata version mismatch

### ISSUE THREAD

**Issue by Keksdroid** [Nolanus/ngx-page-scroll#257]
Hello,
I just wanted to update from 4.0.0-beta-11 to 4.0.1, but I'm getting the following error:
`ERROR in Metadata version mismatch for module .../node_modules/ngx-page-scroll/src/ngx-page-scroll.directive.d.ts, found version 4, expected 3, resolving symbol AppModule in .../src/app/
app.module.ts, resolving symbol AppModule in .../src/app/app.module.ts`

I installed the new version by running 'npm install ngx-page-scroll --save' and changed everything in my code from ng2 to ngx. 
Angular Version is 4.4.6. Is that maybe the problem? Is version 5 required now?

**Comment by moffer** [comment]
I was at version 4.0.0, everything work. Now a new npm install says the same error as above.

**Comment by mikebrsv** [comment]
Same error here. Updated from ng2-page-scroll 4.0.0-beta-11 to ngx-page-scroll 4.0.1 on Angular 4.4.6.

**Comment by adamdport** [comment]
Rolling back to v4.0.0 gets me by for now, `npm install ngx-page-scroll@4.0.0`

**Comment by Nolanus** [comment]
Please try the latest v4.0.2 release. The metadata.json files are generated with angular 4 compiler again to keep them backward compatible.
