### ISSUE TITLE
Feature request: CSS Active class? (ie: scroll spy)

### ISSUE THREAD

**Issue by roypeled** [Nolanus/ngx-page-scroll#262]
Would it be possible to add a directive which will add a specified css class when the target element is within the viewport?

**Comment by Nolanus** [comment]
Hi,

thanks for the suggestions but as mentioned in https://github.com/Nolanus/ngx-page-scroll/wiki/FAQ#is-it-possible-to-detect-the-current-scroll-section this is already a part of other libraries and I want to keep this one as lean as possible
