### ISSUE TITLE
Callback function after page scroll

### ISSUE THREAD

**Issue by gang-qiu** [Nolanus/ngx-page-scroll#275]
I am programmatically triggering a scroll via `pageScrollService.start(pageScrollInstance)`. I want to be able to trigger a callback function after this scroll event. How can I do this?

The `pageScrollFinishListener` that can be supplied to the option is an event Emitter, which doesn't really help. 

I'm aware that I can hook into the `pageScrollFinish` event and pass in a callback that way, but I need to invoke this callback programmatically. 

Ideally, I'd like something like...
```
let pageScrollInstance: PageScrollInstance = PageScrollInstance.newInstance({document: this.document, scrollTarget: '.headingClass', afterScrollCallback: doSomething});
         this.pageScrollService.start(pageScrollInstance)

doSomething(success: boolean) {
   // callback function
}
```

**Comment by Nolanus** [comment]
You may create an EventEmitter, subscribe to it and and supply it to the options:

```typescript
import { EventEmitter } from '@angular/core';

const event = new EventEmitter<boolean>();
event.subscribe((targetReached) => console.log('end of scroll ' + targetReached));
const pageScrollInstance: PageScrollInstance = PageScrollInstance.newInstance({document: this.document, scrollTarget: '#setup', pageScrollFinishListener: event});
this.pageScrollService.start(pageScrollInstance);
```

http://plnkr.co/edit/ThWSkMetMTeBpI6pjGT4?p=preview

**Comment by gang-qiu** [comment]
Wasn't aware of that feature. Thank you!
