### ISSUE TITLE
Scroll duration shorter that interval length, jumping to target

### ISSUE THREAD

**Issue by elias-garcia** [Nolanus/ngx-page-scroll#289]
Hi, I was using this module with Angular 4 and now I've updated the project to Angular 5 and the scroll is not working anymore. On tablets it sometimes works but in PC's not. It's not throwing any error but always displays this message: `Scroll duration shorter that interval length, jumping to target`.

This is my code anyways:

```
<div *ngFor="let coupon of coupons | orderBy : selectedOrder; let index = index">
        <div [id]="cupon.idTrabajoCupon"
             *ngIf="(coupon | couponsByTerm: searchTerm) && (coupon?.idActualState | couponsByState: selectedFilter)">
            <crm-coupon-item> [coupon]="coupon"
                                  [expand]="isExpand[index]"
                                  (onExpand)="expand($event, index, coupon)"></crm-coupon-item>
        </div>
</div>
```

```
@Component({
    selector: 'crm-coupons-list',
    templateUrl: './coupons-list.component.html',
    styleUrls: ['./coupons-list.component.css'],
})
export class CouponsListComponent implements OnInit {

    constructor(
        @Inject(DOCUMENT) private document: any,
        private elementRef: ElementRef,
        private pageScrollService: PageScrollService,
    ) {}

    ngOnInit() {
        PageScrollConfig.defaultScrollOffset = 50;
        PageScrollConfig.defaultDuration = 0;
    }

    expand(e, index, cupon) {
        const pageScrollInstance = PageScrollInstance.simpleInstance(
            this.document,
            `#${cupon.idTrabajoCupon}`,
            this.elementRef.nativeElement
        );
        this.pageScrollService.start(pageScrollInstance);
    }

}
```

**Comment by Nolanus** [comment]
Sorry for this awful late answer, but just for the record:
It looks like the defaultScrollDuration is set to 0, meaning it should perform the scroll animation within 0ms.
Scroll animation is performed by adjusting the `scrollTop` position over time, so adjusting it e.g. every 150ms. However, the total scroll duration you defined (0ms) is smaller than the update interval for the `scrollTop` property. The library detects that and jumps to the target right away. Jumping to the target in my opinion is the desired behaviour in this case, as it "scrolls" to the target within 0ms (=> instantly).
