### ISSUE TITLE
Scrolling does not work with ng-sidebar

### ISSUE THREAD

**Issue by mpGitHub** [Nolanus/ngx-page-scroll#298]
I am unable to get the scrolling to work with the ng-sidebar package. I am using Angular 4.4.6 along with the latest ngx-page-scroll and ng-sidebar. 

If I comment out the ng-sidebar components it works as expected. Is there a possible workaround for this?

I included a simplified snippet of the HTML
[sidebar-example.txt](https://github.com/Nolanus/ngx-page-scroll/files/1662041/sidebar-example.txt)

Thoughts?

**Comment by Nolanus** [comment]
Hi,
it sounds like the usage of ng-sidebar changes the HTML structure and this affects the view that should be scrolled (it's probably not the <body> any more).
Please refer to https://github.com/Nolanus/ngx-page-scroll/wiki/Using-the-right-scrolling-view on how to find the correct "scrolling view".

**Comment by antoine10245** [comment]
👍 +1
