### ISSUE TITLE
Href is going to the link and not scrolling

### ISSUE THREAD

**Issue by hassanasad** [Nolanus/ngx-page-scroll#300]
I am using:

```
Angular CLI: 1.6.7
Node: 9.3.0
OS: darwin x64
Angular: 5.2.3
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.6.7
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

I am trying to use the basic example such as:
```
<a pageScroll href="#section-supplier">Goto Supplier</a>

<div id="section-supplier">HERE</div>
```

Its not preventing the link to navigating away. Is something very basic that i am missing?

**Comment by hassanasad** [comment]
Anyone?

**Comment by Nolanus** [comment]
Hi,

according to the details given there is no obvious error. I assume you installed the library and imported the NgxPageScrollModule into your app.
Are there any errors or warnings in the console?
In addition to that its usually helpful to create a plunkr of the usage of the pageScroll library to showcase the erroneous behaviour.

**Comment by hassanasad** [comment]
Hi

Yeah i am following the demo and am not getting any errors. But am also not
able to make it work. The link href goes to the link value.

**Comment by Nolanus** [comment]
Unfortunately with the given details it's not possible to reproduce your problem.
As you mentioned clicking the link results in a page reload/redirect, consider [activating the "keep logs upon navigation" in Chrome developer tools](https://stackoverflow.com/questions/5327955/how-to-make-google-chrome-javascript-console-persistent) to make sure possible errors aren't missed.

**Comment by hassanasad** [comment]
Already tried that - i dont get any errors :(

**Comment by marzn** [comment]
Can you share your project?

**Comment by fredericojesus** [comment]
It seems routerLink is mandatory. You need to put your route in [routerLink]="['yourRoute']".
