### ISSUE TITLE
angular 6 support?

### ISSUE THREAD

**Issue by AndreyKotofotoff** [Nolanus/ngx-page-scroll#306]
warning " > ngx-page-scroll@4.0.2" has incorrect peer dependency "@angular/core@>=4.2.6 <6.0.0".
warning " > ngx-page-scroll@4.0.2" has incorrect peer dependency "@angular/common@>=4.2.6 <6.0.0".
warning " > ngx-page-scroll@4.0.2" has incorrect peer dependency "@angular/platform-browser@>=4.2.6 <6.0.0".
warning " > ngx-page-scroll@4.0.2" has incorrect peer dependency "@angular/router@>=4.2.6 <6.0.0".

**Comment by Nolanus** [comment]
Angular 6 support was added with version 5.0.0 🙂

**Comment by lukenconsulting** [comment]
npm WARN ngx-page-scroll@5.0.0 requires a peer of @angular/core@>=6.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-page-scroll@5.0.0 requires a peer of @angular/common@>=6.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-page-scroll@5.0.0 requires a peer of @angular/platform-browser@>=6.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-page-scroll@5.0.0 requires a peer of @angular/router@>=6.0.0 <7.0.0 but none is installed. You must install peer dependencies yourself.
