### ISSUE TITLE
 install version v4.0.0

### ISSUE THREAD

**Issue by AhmedAYAT** [Nolanus/ngx-page-scroll#310]
Hello ,
I tried to install ngx-page-scroll version 4.0.0 using npm command line "npm i --save ng2-page-scroll@v4.0.0".
 Unfortunately  i have this error message "No matching version found for ng2-page-scroll@4.0.0"
Could you please add this version, thanks.

**Comment by Nolanus** [comment]
The library has been renamed to `ngx-page-scroll` since version 4, so try `npm i --save ngx-page-scroll@v4.0.0`

**Comment by AhmedAYAT** [comment]
Thanks for your quick reply, I succeed to install the package.
Thanks a lot
