### ISSUE TITLE
Deprecate ng2-page-scroll

### ISSUE THREAD

**Issue by MatthiasKunnen** [Nolanus/ngx-page-scroll#314]
A current project is using _ng2-page-scroll_ and I was wondering why it wasn't getting any updates since 4.0.0-beta.12. It wasn't directly clear for me that the name changed (see #164) since there is no notice of any kind. I don't seem to be alone with this since the amount of downloads of the _ng2_ version is double of the _ngx_.

I would recommend deprecating _ng2-page-scroll_ and pointing project maintainers to _ngx-page-scroll_ in the deprecation message. See https://docs.npmjs.com/cli/deprecate.

**Comment by Nolanus** [comment]
Hi, thanks for pointing that out. Not sure why npm lost the deprecation, as I'm pretty sure the package has been marked as deprecated (#253).

It's now marked as deprecated (again).
