### ISSUE TITLE
Import error with Universal Starter and tsc

### ISSUE THREAD

**Issue by SoftwareAndOutsourcing** [Nolanus/ngx-page-scroll#323]
Hi,

After upgrading my project to the latest Universal Starter version I'm getting an `Unexpected token import` with server side rendering.

 Seems this is related to https://github.com/angular/universal-starter/pull/626 as it worked fine with Webpack and to #212.

I can provide a sample repository if needed.

Thanks.

**Comment by Nolanus** [comment]
I'm currently moving this module to be build with `ng-packagr` support from angular/cli. This should increase the compatibility of the generated packages in various environments.
Unfortunately I can't give an estimation when it will be done...

**Comment by sebastianhaeni** [comment]
This makes this otherwise great package unusable for people using `@angular/universal`.

If anybody is looking for an alternative library, I've migrated to [ngx-scroll-to](https://github.com/nicky-lenaers/ngx-scroll-to) with success. The only thing I'm missing is a global config.

**Comment by Mysame** [comment]
Fastest way to reproduce is adding ngx-page-scroll to https://github.com/enten/angular-universal .

**Comment by arun-maddheshia** [comment]
any chances to fix 🐛  ?

**Comment by Nolanus** [comment]
With version 6 ngx-page-scroll should support SSR. Appreciating your feedback!

**Comment by arun-maddheshia** [comment]
@Nolanus thanx its work perfectly :tada:
