### ISSUE TITLE
ng upgrade issue

### ISSUE THREAD

**Issue by sankp** [Nolanus/ngx-page-scroll#326]
Hello My application having version "ng2-page-scroll": "4.0.0-beta.11",
I am trying to upgrade angular to angular 6 but running into upgrade issue due to this.
Is it supported with angular 6 ?
![image](https://user-images.githubusercontent.com/9613276/45575414-0e751180-b839-11e8-895d-c745062ec81a.png)

**Comment by Nolanus** [comment]
Hi,

Please note that ng2-page-scroll is deprecated and not compatible with
angular 6. You'll have to upgrade to ngx-page-scroll module

Sandeep Parmar <notifications@github.com> schrieb am Fr., 14. Sep. 2018,
23:13:
