### ISSUE TITLE
pageScrollFinishListener usage? [help wanted]

### ISSUE THREAD

**Issue by zurie** [Nolanus/ngx-page-scroll#327]
How can I use the pageScrollInstance to detect that one of my scrolling targets has finished scrolling?

I see how to do it using the directive but I am not sure how to using the pageScrollInstance?

Can you give a example when the scrolling has finished it fires off another function? thanks!

**Comment by Nolanus** [comment]
Hi,

this may be achieved as follows:

```
const event = new EventEmitter<boolean>();
event.subscribe((val) => {
    console.log(val);
});
const pageScrollInstance: PageScrollInstance = PageScrollInstance.newInstance({document: this.document, scrollTarget: '.target', pageScrollFinishListener: event});
```
        
Side note: [Some call(ed)](https://stackoverflow.com/questions/36076700/what-is-the-proper-use-of-an-eventemitter) for not using `EventEmitter` like that, however, only publicly documented methods are used. In a future this might be changed to use rxjs subjects.

**Comment by zurie** [comment]
awesome, works just like I need thanks!  I
