### ISSUE TITLE
Scroll a little less when Navbar is sticky

### ISSUE THREAD

**Issue by brugh** [Nolanus/ngx-page-scroll#331]
If you have a sticky navbar of say 50px height, that 50px get hidden by the navbar as the pagescroll puts the #tag at 0 height. would be nice to be able to configure an additional height for the scroller to jump to.

**Comment by Nolanus** [comment]
As you maybe found out yourself, this may be achieved by using the `scrollOffset` setting on either the directive, pageScrollInstance of setting it application-wide by pageScrollConfig.
