### ISSUE TITLE
Wrong configuration in Readme

### ISSUE THREAD

**Issue by MisuleT** [Nolanus/ngx-page-scroll#341]
Hi Sebastian, 

if you can import NgxPageScrollCoreModule to application you need write with NgxPageScrollCoreModule.forRoot() because there is error like this

logger.service.ts:60 Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[PageScrollService -> InjectionToken ngxps_config]: 
  StaticInjectorError(Platform: core)[PageScrollService -> InjectionToken ngxps_config]: 
    NullInjectorError: No provider for InjectionToken ngxps_config!

It is just for your information.

Have a nice day :)
Michelle

**Comment by Nolanus** [comment]
Hi @MisuleT,
thanks for pointing that out. I committed a fix for that which will be included in the next release.

**Comment by MasterBroki** [comment]
> Hi Sebastian,
> 
> if you can import NgxPageScrollCoreModule to application you need write with NgxPageScrollCoreModule.forRoot() because there is error like this
> 
> logger.service.ts:60 Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[PageScrollService -> InjectionToken ngxps_config]:
> StaticInjectorError(Platform: core)[PageScrollService -> InjectionToken ngxps_config]:
> NullInjectorError: No provider for InjectionToken ngxps_config!
> 
> It is just for your information.
> 
> Have a nice day :)
> Michelle
Just saved my life, thanks!

**Comment by frahmantamala** [comment]
Failed: StaticInjectorError(DynamicTestModule)[InjectionToken ngxps_config]: 
  StaticInjectorError(Platform: core)[InjectionToken ngxps_config]: 
    NullInjectorError: No provider for InjectionToken ngxps_config!

hi, I have the same issue when running karma

**Comment by frahmantamala** [comment]
Hi, there's the same error when running unit test
Failed: StaticInjectorError(DynamicTestModule)[InjectionToken ngxps_config]:
          StaticInjectorError(Platform: core)[InjectionToken ngxps_config]:
            NullInjectorError: No provider for InjectionToken ngxps_config!

import { NGXPS_CONFIG, defaultPageScrollConfig } from 'ngx-page-scroll-core';

in file spec.ts property provider TestingModule I inject this
{ provide: NGXPS_CONFIG, useValue: defaultPageScrollConfig }

**Comment by turbolego** [comment]
This worked for me:

`import {NgxPageScrollCoreModule} from 'ngx-page-scroll-core';`

And then:

`      imports:[
        NgxPageScrollCoreModule.forRoot(),`
