### ISSUE TITLE
Angular 8 Upgrade

### ISSUE THREAD

**Issue by subramn** [Nolanus/ngx-page-scroll#359]
Hi,

After i upgraded my project to use Angular 8, i am getting a compilation errors on npx-page-scroll as it references DOCUMENT which is not obsoleted in Angular 8

import { DOCUMENT } from "@angular/platform-browser";

Any suggestions how to fix this?

**Comment by gleycerparra** [comment]
Import from @angular/common instead.

**Comment by Nolanus** [comment]
Hi @subramn, as @gleycerparra already pointed out, `DOCUMENT` is not exported from `@angular/platform-browser` any longer (see https://github.com/angular/angular/pull/28117). It has been deprecated for a while and is now only exported from `@angular/common` (https://angular.io/api/common/DOCUMENT):

    import { DOCUMENT } from "@angular/common";
