### ISSUE TITLE
Trying to add default custom easing logic throws error on optimized compilation

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [Nolanus/ngx-page-scroll#362]
Hello,

I'm upgrading to version 6 of ngx-page-scroll.
I would like to define defaults in my app.module like this:

    NgxPageScrollCoreModule.forRoot({
      duration: 250,
      scrollOffset: 50,
      interruptible: false,
      easingLogic: (t: number, b: number, c: number, d: number): number => {
        // http://www.timotheegroleau.com/Flash/experiments/easing_function_generator.htm
        let ts: number = (t /= d) * t;
        let tc: number = ts * t;
        return b + c * (tc + -3 * ts + 3 * t);
      }
    }),
    NgxPageScrollModule,

this works, until I try to compile for production (optimize on).
Then angular-cli compile gives this error:

ERROR in Error during template compile of 'AppModule'
  Function expressions are not supported in decorators in 'ɵ0'
    'ɵ0' contains the error at src\app\app.module.ts(99,20)
      Consider changing the function expression into an exported function.

So I should define the easing function somewhere else. Any pointers on how to do that?

Best regards,

Lander

**Comment by Nolanus** [comment]
Hi @LanderBeeuwsaert,
have you tried a similar approach that this solution: https://github.com/auth0/angular2-jwt/issues/537 ?

**Comment by LanderBeeuwsaert** [comment]
And jep, that did the trick.
Thanks @Nolanus
