### ISSUE TITLE
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by andrefarzat** [Nolanus/ngx-page-scroll#363]
Once the versions 5.x were unpublished from npm, we needed to upgrade to 6.x
Following the [small tutorial](https://github.com/Nolanus/ngx-page-scroll/issues/88#issuecomment-456824209) from the README.md, we are facing this issue (both on mac and windows machines):

<img width="807" alt="Screen Shot 2019-06-03 at 19 05 22" src="https://user-images.githubusercontent.com/649219/58838046-d7979380-8633-11e9-9408-7d91ee031636.png">

<img width="1792" alt="Screen Shot 2019-06-03 at 19 16 03" src="https://user-images.githubusercontent.com/649219/58838108-0e6da980-8634-11e9-8317-431ec7d0cb2a.png">

The package.json is here: https://pastebin.com/uFgVXJH4

Digging on the code, if we change from `ɵɵdefineInjectable` to `defineInjectable` and from `ɵɵinject` to `inject` the code works. Can you see why this is happening ?

**Comment by tfohlmeister** [comment]
I can reproduce this error and confirm that downgrading `ngx-page-scroll-core` to `6.0.0` fixes this issue.

**Comment by andrefarzat** [comment]
Regarding the diff: https://github.com/Nolanus/ngx-page-scroll/compare/v6.0.0...v6.0.1
the main difference is the angular version which now is 8.x

I will downgrade to 6.0.0 ( forcing it on package.json ) while this isn't fixed

**Comment by Nolanus** [comment]
Hi,

v5 is still [available via npm](https://www.npmjs.com/package/ngx-page-scroll/v/5.0.1) and can be installed via `npm install ngx-page-scroll@5.0.1`.

Cause for the reported problem is a change in the compiled bundles which I overlooked (see https://github.com/angular/angular/issues/30413). I'll release a new v6 version compiled using angular 7 tools shortly to fix this.

**Comment by Nolanus** [comment]
@andrefarzat, please check the behaviour with `v6.0.2` and let me know whether it's working.
