### ISSUE TITLE
How to use with Angular Material?

### ISSUE THREAD

**Issue by spock123** [Nolanus/ngx-page-scroll#364]
Hi, this might not be an issue per se, but has anyone gotten this module to work when used with Angular Material?

When using a mat-sidenav-container no scrolling seems to work. I know it's something Material does, but has anyone gotten this module to work within a mat-sidenav-container?

Cheers for a great module

**Comment by Nolanus** [comment]
Hi @spock123,

that's possible by defining the view that should be scrolled. Using the material sidenav component adds a new DOM element that will be scrolled. Get hold of the `MatScrollContent` instance, get the `elementRef` and pass the `nativeElement` of that to the `pageScrollService`:

    // Template:
    <mat-sidenav-content #content>
    
    // Component:
    @ViewChild('content', {static: false})
    public readonly sideNavContent: MatDrawerContent;
    
    // Component method:
    
    this.pageScrollService.scroll({
      document: this.document,
      scrollTarget: '.theEnd',
      scrollViews: [this.sideNavContent.getElementRef().nativeElement],
    });

It should also work without the template reference variable, however that didn't work as expected in my short test.
You may find a working example at https://stackblitz.com/edit/angular-nrnrjq

**Comment by spock123** [comment]
@nolanus Thank you so much, great stuff!!

**Comment by dd86** [comment]
@Nolanus Please let us know when  ngx-page-scroll for Angular8 will be released. Currently it is not working with V8. Waiting for it . Thanks in advance.

**Comment by Nolanus** [comment]
This libraries version 6 compatible with angular v8. However, the upcoming releases of this library will no longer support angular v7.
