### ISSUE TITLE
Is there a way to make scroll look smoother?

### ISSUE THREAD

**Issue by StevRoger** [Nolanus/ngx-page-scroll#394]
I am using ngx page scroll in my project but scrolling isn't smooth as I expected. It's currently about 15-20 fps I am not sure. Can I make it smoother?

**Comment by Nolanus** [comment]
Hi @StevRoger,
sounds like that either the device is not that powerful or the page you're scrolling has much content that needs to be redrawn.
You may try to tweak the `_interval` property of the settings: https://github.com/Nolanus/ngx-page-scroll/blob/master/projects/ngx-page-scroll-core/src/lib/types/page-scroll.config.ts#L9
This library does not offload anything but just updates the scroll position every `_interval` seconds. Maybe that helps?
