### ISSUE TITLE
Angular 9

### ISSUE THREAD

**Issue by achimha** [Nolanus/ngx-page-scroll#404]
Any plans to update the package for Angular 9?

**Comment by Nolanus** [comment]
Hi @achimha, the latest version if the library (v7) should already be able to work within an angular 9 environment. Please let me know in case you experience any issues.

**Comment by achimha** [comment]
No apparent issues but npm shows a version conflict warning and Angular 9 is now officially released.

**Comment by S1nPur1ty** [comment]
I am facing the same issue:

'''
This likely means that the library (ngx-page-scroll-core) which declares NgxPageScrollCoreModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
'''

**Comment by damodog** [comment]
I'm working on a project in Angular 9 and am having issues referencing the Node packages in my app.module file when importing.

<img width="1192" alt="Screenshot 2020-07-22 at 09 43 40" src="https://user-images.githubusercontent.com/1637410/88165344-76eb6180-cc0d-11ea-9bb1-d4f6111e9162.png">

With `ng serve` running:

<img width="824" alt="Screenshot 2020-07-22 at 11 22 14" src="https://user-images.githubusercontent.com/1637410/88165647-ee20f580-cc0d-11ea-9774-f3d175289a07.png">

If I change the path to look for the the package module files the error disappears:

<img width="895" alt="Screenshot 2020-07-22 at 11 20 48" src="https://user-images.githubusercontent.com/1637410/88165743-1872b300-cc0e-11ea-94c9-a64827da7cbb.png">

But the paths in the package files are now erroring?
<img width="1000" alt="Screenshot 2020-07-22 at 11 26 48" src="https://user-images.githubusercontent.com/1637410/88165866-4657f780-cc0e-11ea-93dd-4c888c2c4f9e.png">

Angular CLI: 9.1.6
Node: 12.16.3
OS: darwin x64

Angular: 9.0.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.7
@angular-devkit/build-angular      0.900.7
@angular-devkit/build-ng-packagr   0.900.7
@angular-devkit/build-optimizer    0.900.7
@angular-devkit/build-webpack      0.900.7
@angular-devkit/core               9.0.7
@angular-devkit/schematics         9.1.6
@angular/cdk                       9.2.3
@angular/cli                       9.1.6
@angular/material                  9.2.3
@ngtools/webpack                   9.0.7
@schematics/angular                9.1.6
@schematics/update                 0.901.6
ng-packagr                         9.1.3
rxjs                               6.5.5
typescript                         3.7.5
webpack                            4.41.2

**Comment by Nolanus** [comment]
Hi all. Sorry for the inconvenience, there was a problem with v7.0.2, resulting in the released files to be unusable for angular projects. v7.0.3 should fix this, please update to that version and let me know in case there any problems.
