### ISSUE TITLE
Unit tests give warning about instance of PageScrollService already exists

### ISSUE THREAD

**Issue by ColinMorris83** [Nolanus/ngx-page-scroll#410]
Why do unit tests that import the core module produce the following warning:
An instance of PageScrollService already exists, usually including one provider should be enough, so double check

Is the service supposed to be providedIn: 'root' ? You have to import the module in order for the ngxps_config injection token to be set, and the module provides the service.

**Comment by Nolanus** [comment]
The service is supposed to be used a as singleton and declared as `providedIn: 'root'`. The message does not affect the functionality though
