### ISSUE TITLE
Angular 10 doesn't compile "7.0.2"

### ISSUE THREAD

**Issue by iBaff** [Nolanus/ngx-page-scroll#414]
In Version "ngx-page-scroll": "7.0.2" and "ngx-page-scroll-core": "^7.0.2" angular **does not** compile the two packages to esm.

A downgrade to "7.0.1" fixes the problem:

```bash
$ ng serve
Compiling ngx-page-scroll-core : es2015 as esm2015
Compiling ngx-page-scroll : es2015 as esm2015
```

**Comment by Nolanus** [comment]
Hi. Sorry for the inconvenience, there was a problem with v7.0.2, resulting in the released files to be unusable for angular projects. v7.0.3 should fix this, please update to that version and let me know in case there any problems.
