### ISSUE TITLE
Error while compiling with Angular 9

### ISSUE THREAD

**Issue by luisferreira90** [Nolanus/ngx-page-scroll#416]
After the latest minor update, from 7.0.1 to 7.0.3, I can't compile my Angular 9 application. This error always appears:

```
Warning: Invalid constructor parameter decorator in /Users/miguelf90/website/web/node_modules/ngx-page-scroll-core/fesm2015/ngx-page-scroll-core.js:
 () => [
    { type: undefined, decorators: [{ type: Inject, args: [NGXPS_CONFIG,] }] }
]
Error: Error on worker #8: Error: getInternalNameOfClass() called on a non-ES5 class: expected PageScrollService to have an inner class declaration
```

If I downgrade to 7.0.1 everything works perfectly again.

**Comment by skyleguy** [comment]
same issue here

**Comment by Nolanus** [comment]
Hi,
could you please elaborate on that and provide some details on how you integrate the library (root or lazy loaded module, with custom configuration or without), which angular versions you're using, compilation settings and compilation commend.

I just tried to reproduce the problem with an angular project environment set up by the angular/cli (version 9.1.12) and wasn't able to get the mentioned warning.

Thanks!
