### ISSUE TITLE
Angular 14 update

### ISSUE THREAD

**Issue by JesseDeBruijne** [Nolanus/ngx-page-scroll#445]
Hi,

With my current Angular 14 app I'm getting peer dependency errors about this package because it still references Angular 13.
I can bypass these errors and it works fine.

Can the library be updated to Angular 14? I'd make a PR for it myself but I do not know how to test the package to make sure everything works as expected.

**Comment by Sazeidya** [comment]
Hi,

I opened a pull request for Angular 14 support ([PR](https://github.com/Nolanus/ngx-page-scroll/pull/446)). 
@Nolanus could you please review it and if everything is ok merge it into the project and provide and a new package, please?

Happy weekend!
