### ISSUE TITLE
Angular v15 support

### ISSUE THREAD

**Issue by Sazeidya** [Nolanus/ngx-page-scroll#454]
Hi @Nolanus,

I added a new pull request to add Angular v15 support.

You can find it here: [PR](https://github.com/Nolanus/ngx-page-scroll/pull/453)

Could you please review it and if everything is okay, provide a new version please?

Thank you very much. :)

**Comment by Sazeidya** [comment]
@Nolanus just giving this a little bump. :)

**Comment by kubica** [comment]
@Nolanus Is there any update on this?

**Comment by Nolanus** [comment]
Hi all. I'll look at it and merge it this weekend.

**Comment by Nolanus** [comment]
Angular v15 support added with library v10. Thanks to @Sazeidya!

**Comment by Sazeidya** [comment]
Thank you for this library. I'm just glad I can give something back! :)
