### ISSUE TITLE
Support Angular 17

### ISSUE THREAD

**Issue by tanMARIS** [Nolanus/ngx-page-scroll#466]
Hello,
please support Angular 17.
Right now I'm getting the unmet peer dependency error.

**Comment by dvut** [comment]
+1

**Comment by kmasuhr** [comment]
+2

**Comment by tiefenauer** [comment]
+3

**Comment by jasedwards** [comment]
There is an open PR for this already.

**Comment by sureshpvja** [comment]
+1

**Comment by Nolanus** [comment]
angular 17 support added with library v12
