### ISSUE TITLE
ng2-page-scroll not working on ie9

### ISSUE THREAD

**Issue by gdisanto** [Nolanus/ngx-page-scroll#71]
It looks like ng2-page-scroll doesn't work on ie9, simply nothing happens and I don't receive any error in the console.

**Comment by Nolanus** [comment]
No console output at all? Try switching to development mode (aka not switching into production mode) in anular. This should produce console warnings if for a certain reason no scroll animation could be started.

Is the "pageScrollFinish" event fired?
Check whether manually (e.g. in the browser console) setting the "scrollTop" value of the desired scrollView to a certain value results in a scroll position change. If not, the scroll view is no the one you wan't (or at least in IE that's not the scrollable view).

**Comment by manueljun17** [comment]
I have the same issue.

It says, "Unable to get property 'endTime' of undefined or null reference" on the debug console in IE9.

Please help
