### ISSUE TITLE
Modularization

### ISSUE THREAD

**Issue by Nolanus** [Nolanus/ngx-page-scroll#88]
Extract core "PageScrollService" and separate it from the "pageScroll" directive for e.g. buttons. This allows usage of the PageScrollService without requiring the "@angular/router" dependency, which is only present in the directive (would resolve #40,#65 and simplify #69,#87).

**Comment by Nolanus** [comment]
Version 6 splits up the library into two npm modules: `ngx-page-scroll-core` and `ngx-page-scroll`.

The NgxPageScrollCore module only contains the `PageScrollService` which handles the actual scroll animation by manipulating the `scrollTop` properties of the DOM objects.

The NgxPageScroll module requires the NgxPageScrollCore module as peer dependency. It provides the directive `pageScroll` for easy drop-in usage of scroll animations.

## How to upgrade:

### Step 1
Replace
```
"dependencies": {
   "ngx-page-scroll": "^5.0.0"
}
```

with

```
"dependencies": {
   "ngx-page-scroll-core": "^6.0.0",
   "ngx-page-scroll": "6.0.0"
}
```

and run `npm install`.

### Step 2

Add the `NgxPageScrollCoreModule` to your app, next to the existing `NgxPageScrollModule`:

```
import { NgxPageScrollCoreModule } from 'ngx-page-scroll-core';
import { NgxPageScrollModule } from 'ngx-page-scroll';

@NgModule({
  imports: [
    NgxPageScrollCoreModule.forRoot({ /* custom settings here */ }),
    NgxPageScrollModule,
  ]
```

Optionally move global setting overrides (like the default duration) into `forRoot()` method call.

**Comment by AckerApple** [comment]
Just one note from my upgrade experience, I had to stop using PageScrollInstance

Before Upgrade
```js
import { PageScrollInstance } from "ngx-page-scroll"

const pageScrollInstance = PageScrollInstance.simpleInstance(document, "#Import AckModule");
this.PageScrollService.start(pageScrollInstance);
```

After Upgrade
```js
import { PageScrollService } from "ngx-page-scroll-core"

constructor(public PageScrollService:PageScrollService){
  this.PageScrollService.scroll({document:document, scrollTarget:"#targetname"})
}
```

**Comment by andorfermichael** [comment]
@Nolanus @AckerApple but what happens with the scrollingViews option for scrolling child components?

**Comment by Nolanus** [comment]
Try:
```
    this.pageScrollService.scroll({
      document: this.document,
      scrollTarget: '#scrollTarget',
      scrollViews: [sideNavContent[0]] // Create JS array with the first match
    });
```

The documentation has to be enhanced, until then please refer to the comments at the `PageScrollOptions` class https://github.com/Nolanus/ngx-page-scroll/blob/2e94ba023cf37d40539db2770f060fd1297832a2/projects/ngx-page-scroll-core/src/lib/page-scroll-instance.ts#L10
